language: objective-c
before_install:
  brew install carthage python3
osx_image: xcode8
env:
- TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=default FBSIMULATORCONTROL_LAUNCH_TYPE=simulator_app
- TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=custom FBSIMULATORCONTROL_LAUNCH_TYPE=simulator_app
- TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=custom FBSIMULATORCONTROL_LAUNCH_TYPE=direct
- TARGET=fbsimctl COMMAND=build
- TARGET=fbsimctl COMMAND=test
- TARGET=fbsimctl COMMAND=e2e-test
- TARGET=fbxctest COMMAND=build
- TARGET=fbxctest COMMAND=test
script: ./build.sh
branches:
  only:
    - master
